@startuml
'https://plantuml.com/class-diagram
class App {
  + folder(sitename: String, author: String, javascript: String, css: String): void
  + main(args: String[]): void
}
class File
class Scanner
class BufferedWriter
class FileWriter
class IOException

App ..> Scanner
App ..> BufferedWriter
App ..> IOException
BufferedWriter ..> FileWriter
FileWriter ..> File

@enduml