@startuml
'https://plantuml.com/class-diagram
class App {
  + readFile(a: String): List<String>
  + sortNames(names: List<String>): List<String>
  + writeFile(fileName: String, names: List<String>): void
  + main(args: String[]): void
}
interface List
class ArrayList
class File
class BufferedReader
class FileReader
class Exception
class IOException
class Collections
class FileWriter
class PrintWriter

App ..> List
App ..> BufferedReader
App ..> IOException
App ..> Collections
App ..> PrintWriter
List <|.. ArrayList
BufferedReader ..> FileReader
FileReader ..> File
Exception <|-- IOException
PrintWriter ..> FileWriter


@enduml