@startuml
'https://plantuml.com/class-diagram
class App {
  + main(args: String[]): void
}

class FileUtility {
  + addFolder(sitename: String, author: String, javascript: String, css: String): void

}
class File
class Scanner
class BufferedWriter
class FileWriter
class IOException

App ..> FileUtility
FileUtility ..> Scanner
FileUtility ..> BufferedWriter
FileUtility ..> IOException
BufferedWriter ..> FileWriter
FileWriter ..> File

@enduml