@startuml
'https://plantuml.com/class-diagram

class App {
     + main(args: String[]): void

}
class ProductSearch {
     + searchProduct(productName: String): String

}
class JSONParser
class JSONArray
class JSONObject
class FileReader
class BufferedReader
class InputStreamReader
class Exception

App ..> ProductSearch
ProductSearch ..> JSONParser
ProductSearch ..> JSONObject
ProductSearch ..> JSONArray
ProductSearch ..> Exception
ProductSearch ..> BufferedReader
BufferedReader ..> InputStreamReader
JSONParser ..> FileReader

@enduml