@startuml
'https://plantuml.com/class-diagram

class App {
  + main(args: String[]): void
}
class ProductSearch {
  + replaceText( filename: String, sourceText: String, replacementText: String ): void
}
class Scanner
class Paths
abstract class Charset
class StandardCharsets
class Files
class IOException
class Exception

App ..> ProductSearch
ProductSearch ..> Scanner
ProductSearch ..> Paths
ProductSearch ..> Files
ProductSearch ..> StandardCharsets
ProductSearch ..> IOException
IOException ..> Exception
Files ..> Charset

@enduml