@startuml
'https://plantuml.com/class-diagram
class App {

  + main(args: String[]): void
}

class FileUtility {
  + readFile(a: String): List<String>
  + writeFile(fileName: String, names: List<String>): void
}

class StringUtility {
  + sortList(names: List<String>): List<String>
}

class File
class BufferedReader
class FileReader
class Exception
class IOException
class Collections
class FileWriter
class PrintWriter

App ..> StringUtility
App ..> FileUtility
StringUtility ..> Collections
FileUtility ..> BufferedReader
FileUtility ..> IOException
FileUtility ..> PrintWriter
BufferedReader ..> FileReader
FileReader ..> File
Exception <|-- IOException
PrintWriter ..> FileWriter


@enduml