@startuml
'https://plantuml.com/class-diagram

class App {
 + main(args: String[]): void
}
class FileUtility {
 + countWords(fileName: String): String
}
class File
class HashMap
class Scanner
class FileNotFoundException

App ..> FileUtility
FileUtility ..> Scanner
FileUtility ..> HashMap
FileUtility ..> FileNotFoundException
FileNotFoundException ..> Exception
Scanner ..> File

@enduml